/// <reference types="mocha" />
import { expect } from "chai";
import * as fs from "node:fs";
import * as path from "node:path";
import type { HttpRequest, HttpResponse } from "./router";
import { createStaticHandler } from "./static";

/**
 * Checks the contract between the web app build (`www/`) and the adapter.
 *
 * The folder is generated by `npm run build:pwa`, so the tests are skipped when it is absent — a checkout
 * without a PWA build must stay green.
 */
const www = path.resolve(__dirname, "..", "..", "..", "www");
const built = fs.existsSync(path.join(www, "index.html"));

describe("web app delivery", () => {
	if (!built) {
		it.skip("is skipped until www/ exists (run npm run build:pwa)", () => undefined);
		return;
	}

	const handler = createStaticHandler({ root: www });

	const request = (pathOfRequest: string, extra: Partial<HttpRequest> = {}): HttpRequest => ({
		method: "GET",
		path: pathOfRequest,
		query: {},
		headers: {},
		body: "",
		remoteAddress: "127.0.0.1",
		...extra,
	});

	const index = fs.readFileSync(path.join(www, "index.html"), "utf8");

	it("ships the app shell, the icons and the service worker", () => {
		for (const file of [
			"index.html",
			"manifest.webmanifest",
			"sw.js",
			"favicon.svg",
			"icon-192.png",
			"icon-512.png",
		]) {
			expect(fs.existsSync(path.join(www, file)), `${file} is part of the build`).to.equal(true);
		}
	});

	it("references its assets relatively, so it also works below a sub path", () => {
		// the adapter's static handler serves the folder as it is; absolute URLs would break the web extension mode
		expect(index).to.not.match(/(src|href)="\/(?!\/)/);
		expect(index).to.contain('src="./assets/');
	});

	it("serves the shell as HTML and the hashed assets with the right type", () => {
		const shell = handler(request("/")) as HttpResponse;
		expect(shell.status).to.equal(200);
		expect(shell.headers["content-type"]).to.equal("text/html; charset=utf-8");
		expect(shell.headers["cache-control"]).to.equal("no-cache");

		const assetPath = /src="\.\/(assets\/[^"]+)"/.exec(index)?.[1];
		expect(assetPath, "script of the app shell").to.be.a("string");
		const asset = handler(request(`/${assetPath}`)) as HttpResponse;
		expect(asset.status).to.equal(200);
		expect(asset.headers["content-type"]).to.equal("text/javascript; charset=utf-8");
		expect(asset.body.length).to.be.greaterThan(1000);
	});

	it("serves the manifest and the icons for the install prompt", () => {
		const manifest = handler(request("/manifest.webmanifest")) as HttpResponse;
		expect(manifest.status).to.equal(200);
		expect(manifest.headers["content-type"]).to.equal("application/manifest+json; charset=utf-8");

		const icon = handler(request("/icon-192.png")) as HttpResponse;
		expect(icon.status).to.equal(200);
		expect(icon.headers["content-type"]).to.equal("image/png");

		const sw = handler(request("/sw.js")) as HttpResponse;
		expect(sw.status).to.equal(200);
		expect(sw.headers["content-type"]).to.equal("text/javascript; charset=utf-8");
	});

	it("answers the deep links of the client side router with the shell", () => {
		for (const route of ["/month", "/reports", "/absences", "/sync", "/profile"]) {
			const response = handler(request(route, { headers: { accept: "text/html" } })) as HttpResponse;
			expect(response.status, route).to.equal(200);
			expect(response.body.toString(), route).to.contain('<div id="root">');
		}
	});
});
