/**
 * Synchronisation service for offline punches.
 *
 * The PWA and the kiosk terminal queue punches locally while they have no connection and send them as a
 * batch afterwards. Every punch carries an idempotency key, so a repeated batch never creates duplicates.
 *
 * Punches that cannot be trusted are **not** discarded: they are stored with `sync_state = conflict` (they do
 * not count in the calculation) and reported back to the caller, so an employee or a manager can resolve them
 * later. Only punches that are clearly invalid (missing key, unusable instant, far in the future) are
 * rejected outright.
 *
 * A "cancellation pair" is a pair of neighbouring punches that lie within a tolerance of each other — usually
 * the result of an accidental double punch. Such pairs can be removed together.
 */

import type { Db } from "../db/database";
import type { EntriesRepository, EntryDirection, EntryRecord, EntrySyncState } from "../db/repositories/entries";
import type { UsersRepository } from "../db/repositories/users";
import { NotFoundError, ValidationError } from "../errors";
import { writeAuditLog } from "../db/repositories/audit";
import { checkEmploymentWindow } from "../domain/punch";
import { addDays, localDate as resolveLocalDate } from "../util/time";
import type { AggregationService } from "./aggregation";

/** Reason why a punch was not accepted as it came in. */
export type SyncConflictReason =
	"missing_key" | "invalid" | "future" | "too_old" | "duplicate_punch" | "clock_skew" | "employment_window";

/** A single punch of an offline batch. */
export interface SyncPunchInput {
	/** Idempotency key generated by the client (mandatory for batches) */
	idempotencyKey: string;
	/** Punch instant, UTC epoch seconds (device time) */
	tsUtc: number;
	/** Instant reported by the client clock (used for the skew check) */
	clientTsUtc?: number | null;
	/** Direction hint for the UI */
	direction?: EntryDirection;
	/** Free-form note */
	note?: string | null;
}

/** Input of a synchronisation batch. */
export interface SyncBatchInput {
	/** Employee the punches belong to */
	userId: number;
	/** Time zone used to derive the local cache fields */
	timeZone: string;
	/** Queued punches (order does not matter, they are sorted by instant) */
	punches: SyncPunchInput[];
	/** Who triggers the synchronisation (the employee itself or an admin) */
	actorId: number;
	/** Client IP address of the actor */
	actorIp?: string | null;
	/** Difference between device and server time tolerated before flagging (`300` seconds) */
	maxClockSkewSeconds?: number;
	/** Punches closer than this to an existing punch are duplicates (`30` seconds) */
	minDistanceSeconds?: number;
	/** Punches further in the future than this are rejected (`12` hours) */
	maxFutureSeconds?: number;
	/**
	 * Queued punches older than this are stored as a conflict instead of counting (`0` = no bound).
	 *
	 * The offline queue is the only way an employee still writes a punch of his own, so the same window that
	 * bounds an own change applies here: an older punch reaches the day and waits for the administration.
	 */
	maxPastSeconds?: number;
	/** Instant of the synchronisation, defaults to now */
	now?: number;
}

/** Punches that were stored (or already existed). */
export interface SyncAccepted {
	/** Key of the client */
	idempotencyKey: string;
	/** Id of the stored punch */
	entryId: number;
	/** False when the punch was already stored earlier */
	created: boolean;
	/** Resulting synchronisation state */
	syncState: EntrySyncState;
	/** Local date the punch belongs to */
	localDate: string;
}

/** Punches that were stored but need a decision. */
export interface SyncConflict {
	/** Key of the client */
	idempotencyKey: string;
	/** Reason of the conflict */
	reason: SyncConflictReason;
	/** Id of the stored punch, `null` when nothing was stored */
	entryId: number | null;
	/** Stored punch, `null` when nothing was stored */
	entry: EntryRecord | null;
}

/** Punches that were not stored at all. */
export interface SyncRejected {
	/** Key of the client */
	idempotencyKey: string;
	/** Reason of the rejection */
	reason: SyncConflictReason;
	/** Human readable detail (e.g. the offending instant) */
	detail: string;
}

/** Result of a synchronisation batch. */
export interface SyncBatchResult {
	/** Stored punches, sorted by instant */
	accepted: SyncAccepted[];
	/** Punches stored as conflict */
	conflicts: SyncConflict[];
	/** Punches that were not stored */
	rejected: SyncRejected[];
	/** Local dates whose day aggregate was refreshed */
	recalculated: string[];
}

/** Input for resolving a conflict. */
export interface ResolveConflictInput {
	/** Id of the punch in conflict */
	entryId: number;
	/** `accept` keeps the punch (optionally with a corrected instant), `dismiss` deletes it */
	action: "accept" | "dismiss";
	/** Corrected instant (UTC epoch seconds) used when accepting */
	tsUtc?: number;
	/** Reason recorded in the audit trail */
	reason?: string | null;
	/** Who resolves the conflict */
	actorId: number;
	/** Client IP address of the actor */
	actorIp?: string | null;
	/** Time zone used to recompute the local cache fields when the instant changes */
	timeZone?: string;
	/** Instant of the decision, defaults to now */
	now?: number;
}

/** Result of resolving a conflict. */
export interface ResolveConflictResult {
	/** Applied action */
	action: "accept" | "dismiss";
	/** Punch after the decision, `null` after a dismissal */
	entry: EntryRecord | null;
	/** Local dates whose day aggregate was refreshed */
	recalculated: string[];
}

/** Two neighbouring punches that cancel each other out. */
export interface CancellationPair {
	/** Earlier punch */
	first: EntryRecord;
	/** Later punch */
	second: EntryRecord;
	/** Distance between both punches in seconds */
	distanceSeconds: number;
}

/** Result of removing a cancellation pair. */
export interface CancelPairResult {
	/** Number of deleted punches */
	removed: number;
	/** Local dates whose day aggregate was refreshed */
	recalculated: string[];
}

/** Synchronisation operations. */
export interface SyncService {
	/** Processes an offline batch */
	sync(input: SyncBatchInput): SyncBatchResult;
	/** Open conflicts of an employee, newest first */
	conflicts(userId: number): EntryRecord[];
	/** Accepts or dismisses a conflict */
	resolve(input: ResolveConflictInput): ResolveConflictResult;
	/** Finds neighbouring punches that cancel each other out */
	findCancellationPairs(
		userId: number,
		fromDate: string,
		toDate: string,
		options?: { maxDistanceSeconds?: number },
	): CancellationPair[];
	/** Removes both punches of a cancellation pair */
	cancelPair(input: {
		entryIds: [number, number];
		reason?: string | null;
		actorId: number;
		actorIp?: string | null;
		now?: number;
	}): CancelPairResult;
}

/** Data sources of the synchronisation service. */
export interface SyncDeps {
	/** Open database handle */
	db: Db;
	/** Punch storage */
	entries: EntriesRepository;
	/** User storage (employment window) */
	users: UsersRepository;
	/** Aggregation service used to refresh the affected days */
	aggregation: AggregationService;
}

/**
 * Creates the synchronisation service.
 *
 * @param deps - data sources
 * @returns service instance
 */
export function createSyncService(deps: SyncDeps): SyncService {
	const { db, entries, users, aggregation } = deps;

	/**
	 * Recalculates the given local dates once.
	 *
	 * @param userId - owner of the days
	 * @param dates - local dates to refresh
	 * @returns the refreshed dates, sorted
	 */
	const refreshDays = (userId: number, dates: Iterable<string>): string[] => {
		const unique = [...new Set(dates)].sort();
		for (const date of unique) {
			aggregation.recalculateDay(userId, date);
		}
		return unique;
	};

	/**
	 * Time zone of an employee (fallback `UTC`).
	 *
	 * @param userId - owner of the punches
	 * @returns IANA time zone
	 */
	const timeZoneOf = (userId: number): string => users.findById(userId)?.timezone ?? "UTC";

	/**
	 * Looks for an existing punch close to the given instant.
	 *
	 * @param userId - owner of the punches
	 * @param tsUtc - instant to check
	 * @param minDistance - tolerated distance in seconds
	 * @param timeZone - time zone used to find the neighbouring days
	 * @returns the nearby punch or `null`
	 */
	const findNearby = (userId: number, tsUtc: number, minDistance: number, timeZone: string): EntryRecord | null => {
		const date = resolveLocalDate(tsUtc, timeZone);
		const candidates = [
			...entries.listByDate(userId, addDays(date, -1)),
			...entries.listByDate(userId, date),
			...entries.listByDate(userId, addDays(date, 1)),
		];
		return candidates.find(entry => Math.abs(entry.tsUtc - tsUtc) < minDistance) ?? null;
	};

	return {
		sync(input: SyncBatchInput): SyncBatchResult {
			const now = input.now ?? Math.floor(Date.now() / 1000);
			const maxSkew = input.maxClockSkewSeconds ?? 300;
			const minDistance = input.minDistanceSeconds ?? 30;
			const maxFuture = input.maxFutureSeconds ?? 12 * 3600;
			const maxPast = input.maxPastSeconds ?? 0;
			const profile = users.getWorkProfile(input.userId);
			const window = { startDate: profile?.startDate ?? null, endDate: profile?.endDate ?? null };

			const accepted: SyncAccepted[] = [];
			const conflicts: SyncConflict[] = [];
			const rejected: SyncRejected[] = [];
			const touched = new Set<string>();

			const sorted = input.punches
				.slice()
				.sort((a, b) => a.tsUtc - b.tsUtc || a.idempotencyKey.localeCompare(b.idempotencyKey));

			for (const punch of sorted) {
				const key = punch.idempotencyKey?.trim() ?? "";
				if (!key) {
					rejected.push({ idempotencyKey: "", reason: "missing_key", detail: "idempotencyKey is required" });
					continue;
				}
				if (!Number.isFinite(punch.tsUtc) || punch.tsUtc <= 0) {
					rejected.push({
						idempotencyKey: key,
						reason: "invalid",
						detail: `tsUtc ${punch.tsUtc} is not a usable instant`,
					});
					continue;
				}
				if (punch.tsUtc > now + maxFuture) {
					rejected.push({
						idempotencyKey: key,
						reason: "future",
						detail: `tsUtc ${punch.tsUtc} is more than ${maxFuture} seconds in the future`,
					});
					continue;
				}

				// a punch that was already transferred is acknowledged without a second write
				const alreadyStored = entries.findByIdempotencyKey(input.userId, key);
				if (alreadyStored) {
					accepted.push({
						idempotencyKey: key,
						entryId: alreadyStored.id,
						created: false,
						syncState: alreadyStored.syncState,
						localDate: alreadyStored.localDate,
					});
					continue;
				}

				// an unrelated punch at almost the same instant is a duplicate and needs a decision
				const duplicate = findNearby(input.userId, punch.tsUtc, minDistance, input.timeZone);
				if (duplicate) {
					conflicts.push({ idempotencyKey: key, reason: "duplicate_punch", entryId: null, entry: null });
					continue;
				}

				const skew = punch.clientTsUtc == null ? 0 : Math.abs(punch.tsUtc - punch.clientTsUtc);
				const windowError = checkEmploymentWindow(punch.tsUtc, window);
				// a queued punch that is older than the window is not lost: it is stored and waits for a decision
				// of the administration instead of counting right away
				const tooOld = maxPast > 0 && punch.tsUtc < now - maxPast;
				const syncState: EntrySyncState = skew > maxSkew || windowError || tooOld ? "conflict" : "synced";

				const stored = entries.insert({
					userId: input.userId,
					tsUtc: punch.tsUtc,
					clientTsUtc: punch.clientTsUtc ?? null,
					timeZone: input.timeZone,
					source: "api",
					direction: punch.direction ?? "auto",
					idempotencyKey: key,
					syncState,
					note: punch.note ?? null,
					actorId: input.actorId,
					actorIp: input.actorIp ?? null,
					now,
				});
				touched.add(stored.entry.localDate);

				if (syncState === "conflict") {
					conflicts.push({
						idempotencyKey: key,
						reason: tooOld ? "too_old" : windowError ? "employment_window" : "clock_skew",
						entryId: stored.entry.id,
						entry: stored.entry,
					});
					continue;
				}
				accepted.push({
					idempotencyKey: key,
					entryId: stored.entry.id,
					created: stored.created,
					syncState: stored.entry.syncState,
					localDate: stored.entry.localDate,
				});
			}

			return { accepted, conflicts, rejected, recalculated: refreshDays(input.userId, touched) };
		},

		conflicts(userId: number): EntryRecord[] {
			return entries.listBySyncState(userId, "conflict");
		},

		resolve(input: ResolveConflictInput): ResolveConflictResult {
			const current = entries.findById(input.entryId);
			if (!current) {
				throw new NotFoundError(`entry ${input.entryId} not found`);
			}
			if (current.syncState !== "conflict") {
				throw new ValidationError(`entry ${input.entryId} is not in conflict (state ${current.syncState})`);
			}

			const now = input.now ?? Math.floor(Date.now() / 1000);
			const touched = new Set<string>([current.localDate]);
			let entry: EntryRecord | null = current;

			if (input.action === "accept") {
				if (input.tsUtc !== undefined && input.tsUtc !== current.tsUtc) {
					const moved = entries.update({
						id: current.id,
						expectedRevision: current.revision,
						patch: { tsUtc: input.tsUtc },
						reason: input.reason ?? "clock skew corrected",
						actorId: input.actorId,
						actorIp: input.actorIp ?? null,
						timeZone: input.timeZone ?? timeZoneOf(current.userId),
						now,
					});
					touched.add(moved.localDate);
					touched.add(current.localDate);
				}
				entry = entries.setSyncState({
					id: current.id,
					syncState: "synced",
					actorId: input.actorId,
					reason: input.reason ?? null,
					actorIp: input.actorIp ?? null,
					now,
				});
				writeAuditLog(db, {
					atUtc: now,
					actorId: input.actorId,
					action: "entry.conflict_accept",
					entity: "time_entry",
					entityId: current.id,
					detail: { userId: current.userId, tsUtc: entry.tsUtc, reason: input.reason ?? null },
					ip: input.actorIp ?? null,
				});
			} else {
				entries.remove({
					id: current.id,
					actorId: input.actorId,
					reason: input.reason ?? "conflict dismissed",
					actorIp: input.actorIp ?? null,
					now,
				});
				writeAuditLog(db, {
					atUtc: now,
					actorId: input.actorId,
					action: "entry.conflict_dismiss",
					entity: "time_entry",
					entityId: current.id,
					detail: { userId: current.userId, tsUtc: current.tsUtc, reason: input.reason ?? null },
					ip: input.actorIp ?? null,
				});
				entry = null;
			}

			return { action: input.action, entry, recalculated: refreshDays(current.userId, touched) };
		},

		findCancellationPairs(
			userId: number,
			fromDate: string,
			toDate: string,
			options?: { maxDistanceSeconds?: number },
		): CancellationPair[] {
			const maxDistance = options?.maxDistanceSeconds ?? 120;
			const punches = entries
				.listByRange(userId, fromDate, toDate)
				.filter(entry => entry.syncState === "synced")
				.slice()
				.sort((a, b) => a.tsUtc - b.tsUtc || a.id - b.id);

			const pairs: CancellationPair[] = [];
			let index = 0;
			while (index + 1 < punches.length) {
				const first = punches[index];
				const second = punches[index + 1];
				const distanceSeconds = second.tsUtc - first.tsUtc;
				if (distanceSeconds >= 0 && distanceSeconds <= maxDistance) {
					pairs.push({ first, second, distanceSeconds });
					// both punches are used, so the next candidate starts after them
					index += 2;
					continue;
				}
				index++;
			}
			return pairs;
		},

		cancelPair(input: {
			entryIds: [number, number];
			reason?: string | null;
			actorId: number;
			actorIp?: string | null;
			now?: number;
		}): CancelPairResult {
			const first = entries.findById(input.entryIds[0]);
			const second = entries.findById(input.entryIds[1]);
			if (!first || !second) {
				throw new NotFoundError("both punches of the cancellation pair must exist");
			}
			if (first.userId !== second.userId) {
				throw new ValidationError("both punches of the cancellation pair must belong to the same employee");
			}

			const now = input.now ?? Math.floor(Date.now() / 1000);
			const reason = input.reason ?? "cancellation pair";
			const touched = new Set<string>([first.localDate, second.localDate]);
			let removed = 0;

			const run = db.transaction((): void => {
				for (const entry of [first, second]) {
					if (
						entries.remove({
							id: entry.id,
							actorId: input.actorId,
							reason,
							actorIp: input.actorIp ?? null,
							now,
						})
					) {
						removed++;
					}
				}
				writeAuditLog(db, {
					atUtc: now,
					actorId: input.actorId,
					action: "entry.cancel_pair",
					entity: "time_entry",
					entityId: `${first.id}+${second.id}`,
					detail: {
						userId: first.userId,
						punch: { first: first.tsUtc, second: second.tsUtc },
						distanceSeconds: second.tsUtc - first.tsUtc,
						reason,
					},
					ip: input.actorIp ?? null,
				});
			});
			run();

			return { removed, recalculated: refreshDays(first.userId, touched) };
		},
	};
}
